(function(){
'use strict';
const {Battle,same,dist}=Waredo,$=id=>document.getElementById(id),art=id=>'../v5/public/assets/characters/'+id+'.png';
let battle=new Battle(),selected='isaac',mode='inspect',draft=null,showThreat=false,speed=1,paused=false,generation=0,dirty=false;
const board=$('board'),cells=[];
for(let y=0;y<6;y++)for(let x=0;x<6;x++){const b=document.createElement('button');b.className='cell';b.dataset.x=x;b.dataset.y=y;b.setAttribute('aria-label',String.fromCharCode(65+x)+(y+1));b.addEventListener('click',()=>tile({x,y}));board.append(b);cells.push(b)}
const cell=p=>cells[p.y*6+p.x];
const img=(id,cl='')=>'<img class="'+cl+'" src="'+art(id)+'" alt="">';
const shape=d=>d.shape==='square'?'자기 중심 '+(d.range*2+1)+'×'+(d.range*2+1):d.shape==='counter'?'주변 8칸 반격':d.shape==='blast'?'사거리 '+d.range+' · 착탄 3×3':'직선 '+d.range+'칸'+(d.penetrates?' · 관통':'');
function loadDraft(){const u=battle.unit(selected),p=battle.plans[selected];draft=p?{path:p.path.map(v=>({...v})),kind:p.kind,target:p.target?{x:p.path.at(-1).x+p.target.x,y:p.path.at(-1).y+p.target.y}:null}:u?{path:[{x:u.x,y:u.y}],kind:'wait',target:null}:null;dirty=false;}
loadDraft();
function choose(id){if(battle.phase!=='계획'||paused)return;if(dirty){tell('확정 또는 취소 후 다른 캐릭터를 선택하세요');return;}selected=id;mode='inspect';loadDraft();render();}
function tell(s){$('hint').textContent=s;}
function setMode(m){if(battle.phase!=='계획'||paused)return;const u=battle.unit(selected);if(!u||u.team!=='아군'||u.hp<=0)return;if(m==='skill'&&u.cd>0)return;mode=m;draft.kind=m==='move'?'wait':m;draft.target=null;dirty=true;if(['square','counter'].includes(battle.definition(u,draft.kind).shape)&&m!=='move')draft.target={...draft.path.at(-1)};render();}
function tile(p){if(battle.phase!=='계획'||paused)return;const u=battle.unit(selected),v=battle.at(p);if(mode==='inspect'){if(v)choose(v.id);return;}if(!u||u.team!=='아군')return;if(mode==='move'){const path=battle.paths(u).get(p.x+','+p.y);if(!path){tell('이 칸까지 이동할 수 없습니다');return;}draft.path=path.map(v=>({...v}));draft.target=null;dirty=true;render();return;}
const origin=draft.path.at(-1);if(!battle.targetable(u,mode,origin,p)){tell('표시된 범위 안에서 선택하세요');return;}draft.target={...p};dirty=true;render();}
function confirm(){const u=battle.unit(selected);if(!u||!draft)return;const kind=mode==='move'?'wait':draft.kind;if(battle.setPlan(u.id,draft.path,kind,draft.target)){dirty=false;mode='inspect';loadDraft();render();tell(u.name+' 행동 확정');}else tell('방향 또는 목표를 먼저 지정하세요');}
function plannedCells(u,p){if(!p||p.kind==='wait')return[];const o=p.path.at(-1),t=p.target?{x:o.x+p.target.x,y:o.y+p.target.y}:o;return battle.cells(u,p.kind,o,t);}
function render(){
 const u=battle.unit(selected),planning=battle.phase==='계획',ally=!!u&&u.team==='아군'&&u.hp>0,def=u?battle.definition(u,'skill'):null;
 $('game').dataset.time=battle.time;$('turn').textContent='TURN '+String(battle.round).padStart(2,'0');$('phase').textContent=planning?'행동 설계':battle.phase;
 $('shards').textContent=battle.shards;$('watch').style.setProperty('--charge',battle.shards*3.6+'deg');$('watch').classList.toggle('full',battle.canShift());$('period').textContent=battle.time;$('stay').textContent=battle.stay?'복귀까지 '+battle.stay+'턴':battle.canShift()?'시간 이동 가능':'파편 충전 중';
 $('timehint').textContent=battle.time==='현재'?(battle.canShift()?'과거 또는 미래를 탭해 즉시 전환':'적 공격 · 적 사살 · 턴 종료로 충전'):'파편 획득 중지 · '+(battle.time==='과거'?'아군 이동 +1':'아군 일반 공격 +3');
 $('past').disabled=$('future').disabled=!battle.canShift();$('speed').textContent=speed+'×';$('objective').textContent='남은 적 '+battle.living().filter(v=>v.team==='적군').length+' / 3';
 $('order').innerHTML=battle.order().map((id,i)=>{const v=battle.unit(id);return'<button class="slot '+(v.team==='적군'?'enemy ':'')+(id===selected?'selected ':'')+(id===battle.active?'active':'')+'" data-id="'+id+'" aria-label="'+(i+1)+'번째 '+v.name+'"><span class="n">'+(i+1)+'</span>'+img(id)+'<span class="mark">'+(battle.plans[id]?.confirmed?'✓':'·')+'</span></button>'}).join('');
 $('party').innerHTML=battle.units.filter(v=>v.team==='아군').map(v=>'<button class="party-unit '+(v.id===selected?'selected':'')+'" data-id="'+v.id+'" '+(!v.hp?'disabled':'')+'>'+img(v.id)+'<span><b>'+v.name+'</b><small>'+v.hp+' / '+v.maxHp+'</small></span><span class="party-status">'+(!v.hp?'×':battle.plans[v.id]?.confirmed?'✓':'—')+'</span></button>').join('');
 for(const b of document.querySelectorAll('[data-id]'))b.onclick=()=>choose(b.dataset.id);
 cells.forEach((b,i)=>{const label=String.fromCharCode(65+i%6)+(Math.floor(i/6)+1);b.className='cell';b.setAttribute('aria-label',label);b.innerHTML='<span class="coord">'+label+'</span>';});
 if(planning&&u&&draft){const origin=draft.path.at(-1);if(mode==='move')for(const path of battle.paths(u).values())cell(path.at(-1)).classList.add('reachable');
 if(mode==='attack'||mode==='skill'){for(let y=0;y<6;y++)for(let x=0;x<6;x++)if(battle.targetable(u,mode,origin,{x,y}))cell({x,y}).classList.add('cast');for(const p of battle.cells(u,mode,origin,draft.target))cell(p).classList.add(battle.definition(u,mode).shape==='counter'?'counter':'effect');}
 if(u.team==='적군'){for(const p of plannedCells(u,battle.plans[u.id]))cell(p).classList.add('enemy-range');}
 for(const p of draft.path)cell(p).classList.add('path');draft.path.slice(1).forEach((p,i)=>cell(p).insertAdjacentHTML('beforeend','<span class="path-step">'+(i+1)+'</span>'));
 }
 if(planning&&showThreat)for(const v of battle.living().filter(v=>v.team==='적군'))for(const p of plannedCells(v,battle.plans[v.id]))cell(p).classList.add('enemy-range');
 if(planning)for(const v of battle.living()){const p=v.id===selected&&draft?draft.path:battle.plans[v.id]?.path;if(p?.length>1&&(v.team==='아군'||v.id===selected||showThreat)){cell(p.at(-1)).insertAdjacentHTML('beforeend','<div class="unit ghost">'+img(v.id)+'</div>');}}
 for(const v of battle.living()){const b=cell(v),enemy=v.team==='적군';b.insertAdjacentHTML('beforeend','<div class="unit '+(enemy?'enemy':'')+'">'+img(v.id)+'</div><div class="hp-track '+(enemy?'enemy':'')+'"><i style="width:'+v.hp/v.maxHp*100+'%"></i></div>'+(v.status||v.counter?'<span class="status-icon">'+(v.status||'반격')+'</span>':''));b.setAttribute('aria-label',String.fromCharCode(65+v.x)+(v.y+1)+' '+v.name+' 체력 '+v.hp);if(v.id===selected)b.classList.add('selected');}
 if(u){$('unitName').textContent=u.name;$('unitRole').textContent=u.team==='아군'?'OPERATOR / '+(u.tag==='과거'?'PAST':'FUTURE'):'ENEMY / INTENT';$('stats').innerHTML='<span>HP <b>'+u.hp+'/'+u.maxHp+'</b></span><span>ATK <b>'+(u.attack+(u.team==='아군'&&battle.time==='미래'?3:0))+'</b></span>';$('moveMeta').textContent=battle.moveRange(u)+'칸 · 도착지 지정';$('attackMeta').textContent=shape(battle.definition(u,'attack'));$('skillLabel').innerHTML=def.name+'<small>'+(u.cd?'재사용 '+u.cd+'턴':shape(def))+'</small>';$('skill').classList.toggle('ultimate',def.ultimate);}
 for(const m of ['move','attack','skill']){$(m).classList.toggle('active',mode===m);$(m).disabled=!planning||!ally||(m==='skill'&&u.cd>0);}
 $('earlier').disabled=$('later').disabled=!planning||!ally||dirty;$('confirm').disabled=!planning||!ally||!dirty||((mode==='attack'||mode==='skill')&&!draft?.target);$('cancel').disabled=!planning||!ally;
 $('execute').disabled=!planning||dirty;$('ready').textContent=battle.living().filter(v=>v.team==='아군'&&battle.plans[v.id]?.confirmed).length+'/'+battle.living().filter(v=>v.team==='아군').length+' 설정 · 미설정은 대기';
 const path=draft?.path,kind=draft?.kind;let review='행동 미설정';if(u&&path){const name=kind==='wait'?'대기':battle.definition(u,kind).name;review=(path.length>1?'이동 '+(path.length-1)+'칸 → ':'')+name;const origin=path.at(-1),affected=kind!=='wait'?battle.cells(u,kind,origin,draft.target):[],hits=battle.living().filter(v=>v.team!==u.team&&affected.some(p=>same(p,v)));if(hits.length)review+=' · '+hits.length+'명 / '+(battle.definition(u,kind).damage+(kind==='attack'&&u.team==='아군'&&battle.time==='미래'?3:0))+' 기본 피해';}
 $('planText').textContent=review;$('threat').classList.toggle('on',showThreat);
 $('hint').textContent=!planning?(battle.active?battle.unit(battle.active).name+' 행동 중':battle.phase):!ally?'적의 이동·공격 예고':mode==='move'?'파란 칸을 탭 → 이동 확정':mode==='attack'?'공격할 방향을 탭하세요':mode==='skill'?(['square','counter'].includes(def.shape)?'표시된 범위를 확인하고 행동 확정':'스킬 목표를 탭하세요'):'이동 · 공격 · 스킬을 선택하세요';
 $('latest').textContent=battle.logs[0]||'적을 탭해 행동을 예측하고, 아군 계획을 세우세요.';
}
function effects(){const events=battle.events.splice(0);for(const e of events){if(e.type==='attack')for(const p of e.cells)cell(p).classList.add('effect','flash');if(e.type==='hit'){const u=battle.unit(e.id),r=cell(u).getBoundingClientRect(),g=$('game').getBoundingClientRect(),n=document.createElement('span');n.className='damage-float '+(e.critical?'crit':'');n.textContent=(e.critical?'CRIT ':'−')+e.damage;n.style.left=r.left-g.left+r.width/4+'px';n.style.top=r.top-g.top+'px';$('floats').append(n);setTimeout(()=>n.remove(),900);cell(u).classList.add('flash');}}}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function execute(){if(dirty||battle.phase!=='계획')return;const token=generation,current=battle;mode='inspect';try{await current.run(async()=>{if(token!==generation)throw new Error('cancelled');render();effects();let elapsed=0;while(elapsed<420/speed){await delay(35);if(token!==generation)throw new Error('cancelled');if(!paused)elapsed+=35;}while(paused){await delay(50);if(token!==generation)throw new Error('cancelled');}});if(token!==generation)return;selected=battle.living().find(v=>v.team==='아군')?.id||selected;loadDraft();render();effects();if(battle.phase==='승리'||battle.phase==='패배')result();}catch(e){if(e.message!=='cancelled'){console.error(e);tell('실행 오류: '+e.message);}}}
function openModal(content){paused=true;$('modalContent').innerHTML=content;$('modal').showModal();}
function closeModal(){paused=false;$('modal').close();}
function help(){openModal('<h2>시간을 읽고,<br>행동을 설계하세요.</h2><ol><li>아군을 선택하고 <b>이동</b>을 누르세요. 파란 칸을 탭하면 도착 잔상이 생깁니다.</li><li><b>일반 공격 / 스킬</b>을 선택하고 방향을 지정한 뒤 <b>행동 확정</b>을 누르세요.</li><li>아군 순서를 바꾸고 <b>계획 실행</b>으로 모든 행동을 순서대로 처리합니다.</li><li>적을 탭하면 이동과 공격 범위가 보입니다. 주황은 영향 범위, 빗금은 반격 구역입니다.</li><li>파편 100을 모으면 시계 옆 <b>과거 / 미래</b>를 즉시 선택할 수 있습니다. 2턴 후 현재로 돌아옵니다.</li></ol><div class="modal-actions"><button class="primary" id="guideClose">전투로 돌아가기</button></div>');$('guideClose').onclick=closeModal;}
function menu(){openModal('<h2>작전 일시정지</h2><p>턴 '+battle.round+' · '+battle.time+' 시간대</p><div class="modal-actions"><button class="primary" id="resume">전투 계속</button><button id="restart">처음부터 다시 시작</button><button id="training">시간 전환 연습 · 파편 100으로 시작</button><button id="fullscreen">전체 화면</button></div><p class="mode-badge">연습은 초기 파편만 변경합니다.</p>');$('resume').onclick=closeModal;$('restart').onclick=()=>reset(false);$('training').onclick=()=>reset(true);$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('game').requestFullscreen?.();};}
function result(){openModal('<div class="eyebrow">OPERATION '+(battle.phase==='승리'?'COMPLETE':'FAILED')+'</div><h2>'+battle.phase+'</h2><p>'+battle.round+'턴 · 생존 아군 '+battle.living().filter(v=>v.team==='아군').length+'명</p><div class="modal-actions"><button class="primary" id="again">다시 도전</button></div>');$('again').onclick=()=>reset(false);}
function reset(charged){generation++;closeModal();battle=new Battle({charged});selected='isaac';mode='inspect';showThreat=false;loadDraft();render();}
for(const m of ['move','attack','skill'])$(m).onclick=()=>setMode(m);$('confirm').onclick=confirm;$('cancel').onclick=()=>{if(dirty){mode='inspect';loadDraft();}else{const u=battle.unit(selected);battle.setPlan(u.id,[{x:u.x,y:u.y}],'wait',null);loadDraft();}render();};
for(const [id,t]of [['past','과거'],['future','미래']])$(id).onclick=()=>{if(battle.shift(t)){render();effects();tell(t+' 시간대 · '+(t==='과거'?'이동력 +1':'일반 공격력 +3'));}};
for(const[id,d]of[['earlier',-1],['later',1]])$(id).onclick=()=>{battle.swap(selected,d);render();};$('execute').onclick=execute;$('speed').onclick=()=>{speed=speed===1?2:1;render();};$('pause').onclick=menu;$('help').onclick=help;$('close').onclick=closeModal;$('modal').addEventListener('cancel',()=>{paused=false;});$('threat').onclick=()=>{showThreat=!showThreat;render();};$('log').onclick=()=>openModal('<h2>전투 기록</h2><div class="log-lines">'+battle.logs.map(l=>'<p>'+l+'</p>').join('')+'</div>');
render();
})();
