(function(root){
'use strict';
const same=(a,b)=>a.x===b.x&&a.y===b.y,dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y),inside=p=>p.x>=0&&p.y>=0&&p.x<6&&p.y<6;
const dirs=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:-1,y:0}];
const templates=[['isaac','아이작','아군',60,8,'과거',1,'line',1,4],['angelica','안젤리카','아군',30,13,'과거',3,'line',3,4],['mercan','메르칸','아군',50,11,'미래',1,'square',4,4],['holy_lancer','신성 창병','적군',50,8,null,2,'line',1,1],['holy_shield','신성 방패병','적군',60,5,null,1,'line',4,1],['tower_guard','철탑 방위병','적군',30,10,null,4,'line',3,0]];
function normal(u){return{name:'일반 공격',shape:u.shape,range:u.range,damage:u.attack,penetrates:u.id==='holy_lancer'};}
function skill(u,time){const ult=!!u.tag&&u.tag===time;const data={isaac:{name:ult?'시간 붕괴':'지진',shape:'square',range:ult?2:1,damage:8,status:'띄워짐'},angelica:{name:ult?'시간 관통 저격':'저격',shape:'line',range:ult?5:4,damage:ult?8:13,penetrates:ult,status:ult?'기절':null},mercan:{name:ult?'시간 단죄':'복수',shape:'counter',range:1,damage:0,enhanced:ult},holy_lancer:{name:'성광 관통',shape:'line',range:3,damage:8,penetrates:true},holy_shield:{name:'성벽 충격',shape:'line',range:2,damage:3,penetrates:true,push:2},tower_guard:{name:'철탑 집중포화',shape:'blast',range:4,damage:8}};return{...data[u.id],ultimate:ult,cooldown:2};}
class Battle{
 constructor({charged=false}={}){this.units=templates.map(([id,name,team,maxHp,attack,tag,range,shape,x,y])=>({id,name,team,maxHp,hp:maxHp,attack,tag,range,shape,x,y,cd:0,status:null,counter:null}));this.round=1;this.time='현재';this.stay=0;this.shards=charged?100:0;this.phase='계획';this.active=null;this.logs=[];this.events=[];this.allyOrder=['isaac','angelica','mercan'];this.prepare();}
 unit(id){return this.units.find(u=>u.id===id)}
 living(){return this.units.filter(u=>u.hp>0)}
 at(p,except){return this.living().find(u=>u.id!==except&&same(u,p))}
 moveRange(u){return 3+(u.team==='아군'&&this.time==='과거'?1:0)}
 definition(u,kind){return kind==='skill'?skill(u,this.time):normal(u)}
 emit(text,event={}){this.logs.unshift(text);this.logs=this.logs.slice(0,40);this.events.push({text,...event});}
 gain(n){if(this.time==='현재')this.shards=Math.min(100,this.shards+n)}
 canShift(){return this.phase==='계획'&&this.time==='현재'&&this.shards>=100}
 shift(time){if(!['과거','미래'].includes(time)||!this.canShift())return false;this.shards-=100;this.time=time;this.stay=2;this.emit(time+' 시간대 진입 · 2턴 유지',{type:'time'});return true}
 order(){const a=this.allyOrder.filter(id=>this.unit(id).hp>0),e=this.living().filter(u=>u.team==='적군').map(u=>u.id),out=[];for(let i=0;i<Math.max(a.length,e.length);i++)for(const list of this.round%2?[a,e]:[e,a])if(list[i])out.push(list[i]);return out}
 swap(id,delta){if(this.phase!=='계획')return;const i=this.allyOrder.indexOf(id),j=i+delta;if(i<0||j<0||j>=this.allyOrder.length)return;[this.allyOrder[i],this.allyOrder[j]]=[this.allyOrder[j],this.allyOrder[i]];}
 paths(u){const found=new Map([[u.x+','+u.y,[{x:u.x,y:u.y}]]]),q=[{x:u.x,y:u.y}];while(q.length){const p=q.shift(),path=found.get(p.x+','+p.y);if(path.length-1>=this.moveRange(u))continue;for(const d of dirs){const n={x:p.x+d.x,y:p.y+d.y},k=n.x+','+n.y;if(!inside(n)||found.has(k)||this.at(n,u.id))continue;found.set(k,[...path,n]);q.push(n)}}return found}
 cells(u,kind,origin,target){const def=this.definition(u,kind),cells=[];if(def.shape==='square'||def.shape==='counter'){for(let y=0;y<6;y++)for(let x=0;x<6;x++)if(Math.max(Math.abs(x-origin.x),Math.abs(y-origin.y))<=def.range&&!same(origin,{x,y}))cells.push({x,y});return cells}
 if(def.shape==='blast'){if(!target)return[];for(let y=0;y<6;y++)for(let x=0;x<6;x++)if(Math.max(Math.abs(x-target.x),Math.abs(y-target.y))<=1)cells.push({x,y});return cells}
 if(!target)return[];const dx=target.x-origin.x,dy=target.y-origin.y;if((dx&&dy)||(!dx&&!dy))return[];const d={x:Math.sign(dx),y:Math.sign(dy)};for(let i=1;i<=def.range;i++){const p={x:origin.x+d.x*i,y:origin.y+d.y*i};if(!inside(p))break;cells.push(p);if(!def.penetrates&&this.at(p,u.id))break}return cells;}
 targetable(u,kind,origin,p){const d=this.definition(u,kind);if(d.shape==='square'||d.shape==='counter')return same(origin,p);if(!inside(p)||same(origin,p))return false;if(d.shape==='blast')return dist(origin,p)<=d.range;return(origin.x===p.x||origin.y===p.y)&&dist(origin,p)<=d.range;}
 setPlan(id,path,kind,target){const u=this.unit(id);if(this.phase!=='계획'||!u||u.hp<=0||u.team!=='아군')return false;if(!path.length||!same(path[0],u)||path.length-1>this.moveRange(u)||path.some((p,i)=>!inside(p)||(i>0&&(dist(p,path[i-1])!==1||this.at(p,id)))))return false;const o=path.at(-1);if(!['wait','attack','skill'].includes(kind)||kind==='skill'&&u.cd>0)return false;if(kind!=='wait'&&!this.targetable(u,kind,o,target||o))return false;this.plans[id]={path:path.map(p=>({...p})),kind,target:target?{x:target.x-o.x,y:target.y-o.y}:null,confirmed:true};return true;}
 ai(u){const foes=this.living().filter(v=>v.team!==u.team),paths=[...this.paths(u).values()];if(!foes.length)return{path:[{x:u.x,y:u.y}],kind:'wait',target:null,confirmed:true};let best={score:-Infinity,path:[{x:u.x,y:u.y}],kind:'wait',target:null,confirmed:true};for(const path of paths){const o=path.at(-1);for(const kind of ['attack',...(u.cd?[]:['skill'])]){const def=this.definition(u,kind),candidates=def.shape==='square'||def.shape==='counter'?[o]:foes.map(v=>({x:v.x,y:v.y}));for(const t of candidates){if(!this.targetable(u,kind,o,t))continue;const cells=this.cells(u,kind,o,t),hits=foes.filter(v=>cells.some(p=>same(p,v))).length,score=hits*100+(kind==='skill'?4:0)-path.length;if(hits&&score>best.score)best={score,path,kind,target:{x:t.x-o.x,y:t.y-o.y},confirmed:true};}}if(best.score<0){const score=-Math.min(...foes.map(v=>dist(o,v)))*3-path.length/10;if(score>best.score)best={score,path,kind:'wait',target:null,confirmed:true};}}return best;}
 prepare(){this.plans={};for(const u of this.living())this.plans[u.id]=u.team==='적군'?this.ai(u):{path:[{x:u.x,y:u.y}],kind:'wait',target:null,confirmed:false};}
 outcome(){if(!this.living().some(u=>u.team==='적군'))this.phase='승리';else if(!this.living().some(u=>u.team==='아군'))this.phase='패배';return this.phase==='승리'||this.phase==='패배';}
 hit(actor,target,amount,status){if(target.hp<=0)return;const critical=(target.status==='띄워짐'||target.status==='기절'),damage=Math.floor(amount*(critical?1.5:1));target.hp=Math.max(0,target.hp-damage);if(status&&target.hp>0)target.status=status;this.emit(actor.name+' → '+target.name+' '+damage+' 피해'+(critical?' · 치명타':''),{type:'hit',id:target.id,damage,critical});if(!target.hp){target.counter=null;target.status=null;if(target.team==='적군')this.gain(30);this.emit(target.name+' 전투 불능',{type:'defeat',id:target.id});}return critical;}
 counters(target){for(const u of this.living()){if(!u.counter||u.team===target.team||u.status||u.counter.seen.includes(target.id)||Math.max(Math.abs(u.x-target.x),Math.abs(u.y-target.y))>1)continue;u.counter.seen.push(target.id);this.hit(u,target,u.attack,u.counter.enhanced?'기절':null);this.emit(u.name+' 반격!',{type:'counter',id:u.id});if(target.hp<=0||target.status==='기절')break;}}
 async run(step=async()=>{}){if(this.phase!=='계획')return false;this.phase='실행';const order=this.order();for(const id of order){if(this.outcome())break;const u=this.unit(id),p=this.plans[id];this.active=id;if(!u||u.hp<=0)continue;if(u.status){this.emit(u.name+' · '+u.status+'으로 행동 취소');await step();continue;}this.emit(u.name+' 행동 시작',{type:'active',id});await step();if(p.path.length>1||p.kind!=='wait')this.counters(u);if(!u.hp||u.status==='기절')continue;let blocked=false;for(let i=1;i<p.path.length;i++){const next={x:u.x+p.path[i].x-p.path[i-1].x,y:u.y+p.path[i].y-p.path[i-1].y};if(!inside(next)||this.at(next,id)){blocked=true;this.emit(u.name+' 경로 충돌 · 후속 공격 취소');break;}u.x=next.x;u.y=next.y;this.counters(u);await step();if(!u.hp||u.status==='기절'){blocked=true;break;}}
 if(blocked||p.kind==='wait')continue;if(p.kind==='skill'&&u.cd>0){this.emit(u.name+' 스킬 재사용 대기');continue;}const def=this.definition(u,p.kind),target=p.target?{x:u.x+p.target.x,y:u.y+p.target.y}:{x:u.x,y:u.y};if(p.kind==='skill')u.cd=3;
 if(def.shape==='counter'){u.counter={seen:[],enhanced:def.enhanced};this.emit(u.name+' · '+def.name,{type:'counter',id});await step();continue;}
 const cells=this.cells(u,p.kind,u,target);this.emit(u.name+' · '+def.name,{type:'attack',id,cells});await step();let critical=false;for(const v of this.living().filter(v=>v.team!==u.team&&cells.some(c=>same(c,v)))){critical=this.hit(u,v,def.damage+(p.kind==='attack'&&u.team==='아군'&&this.time==='미래'?3:0),def.status)||critical;if(def.push&&v.hp){const d={x:Math.sign(v.x-u.x),y:Math.sign(v.y-u.y)};for(let n=0;n<def.push;n++){const next={x:v.x+d.x,y:v.y+d.y};if(!inside(next)||this.at(next,v.id))break;v.x=next.x;v.y=next.y;this.counters(v);if(!v.hp||v.status==='기절')break;}}}
 if(p.kind==='attack'&&u.team==='적군')this.gain(critical?30:10);await step();this.outcome();}
 this.active=null;if(this.outcome())return true;this.gain(10);if(this.time!=='현재'&&--this.stay===0){this.time='현재';this.emit('현재 시간대로 복귀',{type:'time'});}for(const u of this.units){u.cd=Math.max(0,u.cd-1);u.status=null;u.counter=null;}this.round++;this.phase='계획';this.prepare();this.emit('턴 '+this.round+' · 행동을 설계하세요');return true;}
}
const api={Battle,skill,normal,same,dist};if(typeof module!=='undefined')module.exports=api;root.Waredo=api;
})(typeof globalThis!=='undefined'?globalThis:this);
