const test=require('node:test'),assert=require('node:assert/strict'),{Battle,skill}=require('./model.js');
function idle(b){for(const u of b.living())b.plans[u.id]={path:[{x:u.x,y:u.y}],kind:'wait',target:null,confirmed:true};}
test('time costs 100, rejects repeated shift, returns after exactly 2 rounds without shards',async()=>{const b=new Battle({charged:true});assert(b.shift('과거'));assert.equal(b.shards,0);assert(!b.shift('미래'));assert.equal(b.moveRange(b.unit('isaac')),4);assert.equal(b.moveRange(b.unit('holy_lancer')),3);idle(b);await b.run();assert.equal(b.stay,1);assert.equal(b.time,'과거');idle(b);await b.run();assert.equal(b.time,'현재');assert.equal(b.shards,0);});
test('default start has 0 shards; only present accepts shard rewards',()=>{const b=new Battle();assert.equal(b.shards,0);assert(!b.shift('과거'));b.gain(130);assert.equal(b.shards,100);b.shift('미래');b.gain(30);assert.equal(b.shards,0);});
test('path rejects diagonal, occupied cell, off-board and overrange',()=>{const b=new Battle(),u=b.unit('isaac');assert(!b.setPlan(u.id,[u,{x:2,y:3}],'wait'));assert(!b.setPlan(u.id,[u,{x:0,y:4},{x:-1,y:4}],'wait'));assert(!b.paths(u).has('4,4'));assert(!b.setPlan(u.id,[u,{x:2,y:4},{x:3,y:4}],'wait'));});
test('self skill 3x3 has 8 cells and ultimate 5x5 uses same slot',()=>{const b=new Battle({charged:true}),u=b.unit('isaac');u.x=2;u.y=2;assert.equal(b.cells(u,'skill',u,u).length,8);b.shift('과거');assert.equal(b.cells(u,'skill',u,u).length,24);assert.equal(skill(u,b.time).name,'시간 붕괴');});
test('line targeting rejects diagonal and stops at first unit',()=>{const b=new Battle(),u=b.unit('angelica');assert(!b.targetable(u,'attack',u,{x:2,y:3}));b.unit('isaac').x=3;b.unit('isaac').y=2;assert.equal(b.cells(u,'attack',u,{x:3,y:1}).length,2);});
test('future only adds 3 to allied normal damage',async()=>{const b=new Battle({charged:true});b.shift('미래');const u=b.unit('isaac'),e=b.unit('holy_lancer');u.x=1;u.y=2;idle(b);b.setPlan(u.id,[u],'attack',{x:1,y:1});await b.run();assert.equal(e.hp,39);});
test('skill cooldown survives ultimate switching',async()=>{const b=new Battle();idle(b);const u=b.unit('isaac');b.setPlan(u.id,[u],'skill',u);await b.run();assert.equal(u.cd,2);b.shards=100;b.shift('과거');assert.equal(skill(u,b.time).name,'시간 붕괴');assert.equal(u.cd,2);assert(!b.setPlan(u.id,[u],'skill',u));});
test('counter hits each enemy only once and enhanced counter stuns',()=>{const b=new Battle(),m=b.unit('mercan'),e=b.unit('holy_lancer');e.x=4;e.y=3;m.counter={seen:[],enhanced:true};b.counters(e);assert.equal(e.hp,39);assert.equal(e.status,'기절');b.counters(e);assert.equal(e.hp,39);});
test('turn orders alternate and allied swaps do not move enemy slots',()=>{const b=new Battle();const before=b.order();b.swap('isaac',1);const after=b.order();assert.equal(after[0],'angelica');assert.equal(after[1],before[1]);assert.equal(after[3],before[3]);});
test('airborne target receives critical hit; lethal hit ends combat',()=>{const b=new Battle(),u=b.unit('isaac'),e=b.unit('holy_lancer');e.status='띄워짐';b.hit(u,e,8);assert.equal(e.hp,38);b.units.filter(v=>v.team==='적군').forEach(v=>v.hp=0);assert(b.outcome());assert.equal(b.phase,'승리');});
test('AI can finish a battle without overlapping units or negative health',async()=>{const b=new Battle();for(let i=0;i<35&&b.phase==='계획';i++){for(const u of b.living().filter(u=>u.team==='아군'))b.plans[u.id]=b.ai(u);await b.run();const cells=b.living().map(u=>u.x+','+u.y);assert.equal(new Set(cells).size,cells.length);assert(b.units.every(u=>u.hp>=0));}assert(['승리','패배'].includes(b.phase));});
